### ISSUE TITLE
python3.7 no module named v4l2ctl.utils when importing v4l2ctl?

### ISSUE THREAD

**Issue by nigel-ga** [MichaelIsrael/v4l2ctl#3]
Hi there

Sorry, this is probably a really stupid question. Is there a way to solve "no module named v4l2ctl.utils" when importing v4l2ctl with python3.7?

thanks
Nigel.

**Comment by MichaelIsrael** [comment]
Hi Nigel,

No problem. Thanks for the question/feedback.
Did you try using the last version from GitHub?
This was supposedly fixed two weeks ago. (see #1 and #2).
I will try to build a new alpha version for pip this weekend.

Michael

**Comment by nigel-ga** [comment]
Hi Michael

I just tried the Github version now ,that works, thanks for the suggestion.

cheers
Nigel.

**Comment by MichaelIsrael** [comment]
Great. I just published the 0.1a5 to officially fix this.
Cheers
Michael
